spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modu_office?stringtype=unspecified
    username: modu_user
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: 9a2f8c4e6b0d1a3f5h7j8k9l0m1n2o3p4q5r6s7t8u9v0w1x2y3z4a5b6c7d8e9f
    access-token-expiration-milliseconds: 3600000 # 1 hour
    refresh-token-expiration-milliseconds: 604800000 # 7 days
